---
title: "R Notebook"
output: html_notebook
---

### user will input relevant variables

```{r}
pod5_dir <- "data/Example_Data/Example_Data_Custom_Barcodes/NP51_pod5"
bam_file_name <- "SUP.bam"
minimum <- 1300
maximum <- 1600
barcode_arrangement <- "data/Example_Data/Example_Data_Custom_Barcodes/code/7.21.25_NBD_custom_arrangement.toml"
barcode_sequences <- "data/Example_Data/Example_Data_Custom_Barcodes/code/7.21.25_NBD_custom_96_barcodes.fasta"
kit_name <- "custom_barcode"
```

```{r}
## takes user-defined parameters and writes to param.config
file_connection <- file("~/project/params.config", open = "wt")

writeLines(c(
  "params {",
  paste0("\tpod5_dir = '", pod5_dir, "'"),
  paste0("\tbam_file_name = '", bam_file_name, "'"),
  paste0("\tminimum = ", minimum),
  paste0("\tmaximum = ", maximum),
  paste0("\tbarcode_arrangement = '", barcode_arrangement, "'"),
  paste0("\tbarcode_sequences = '", barcode_sequences, "'"),
  paste0("\tkit_name = '", kit_name, "'"),
  "}"
), con = file_connection)

close(file_connection)
```

```{r}
## runs the nextflow script
system("~/miniconda3/bin/conda run -n pipeline_env nextflow run ~/project/main.nf -c ~/project/params.config")

```
